version: "3.8"
services:
    db_mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3308:3306"
        environment:
            - MYSQL_DATABASE=tttn
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - db:/var/lib/mysql
        networks:
            - health-booking-network

    backend_nodejs:
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        depends_on:
            - db_mysql
        image: tdq11111/backend_nodejs_medical
        restart: unless-stopped
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - 8080:8080
        environment:
            - DB_HOST=db_mysql
            - DB_DATABASE_NAME=tttn
            - DB_USERNAME=root
            - DB_PORT=3306
            - DB_PASSWORD=123456
            - DB_DIALECT=mysql
            - REACT_URL= http://localhost
        expose:
            - 8080
        networks:
            - health-booking-network
volumes:
    db:
networks:
    health-booking-network:
        external: true
#docker network create health-booking-network
#docker compose -p backend_health-booking up -d
